### PR TITLE
feat(SegmentGroupControls): add save button

### PR DESCRIPTION
**Pull request by PaulHax**
image

image

### CODE REVIEW

**Comment by Mrchenshangfeng** [comment]
没有用过ts编写代码，请问图中编译报错是什么问题

**Comment by Mrchenshangfeng** [comment]
@PaulHax

**Comment by Mrchenshangfeng** [comment]
请问如何使用，我这边保存成另一个dcm文件，但是再打开dcm文件就是一片黑。

**Comment by Mrchenshangfeng** [comment]
@PaulHax

**Comment by Mrchenshangfeng** [comment]
已经使用你最新的代码

**Comment by PaulHax** [comment]
@Mrchenshangfeng 
Just black DCM?  That is not what I expect.

Please give me the steps you took in English.  Example:
1. I clicked paint tool
2. painted 1 stroke of red
3. etc

And attach the outputed .dcm file

**Comment by Mrchenshangfeng** [comment]
如图步骤

**Comment by Mrchenshangfeng** [comment]
如图所示：

**Comment by Mrchenshangfeng** [comment]
4 step image

**Comment by Mrchenshangfeng** [comment]
5 step

**Comment by Mrchenshangfeng** [comment]
last step

**Comment by Mrchenshangfeng** [comment]
The effect I want is to be able to echo the drawing trace and label on the dcm file

**Comment by PaulHax** [comment]
Ah.  We need to load the base .dcm file you loaded at first, then load the exported .dcm that you have painted.  The background brain .dcm image is a different file than the exported painted .dcm.  

This PR will allow you to connect the exported painted .dcm with the base .dcm file by "Converting to segment group" https://github.com/Kitware/VolView/pull/528

Can also use this button to save a zip that includes both files and automatilcy connects them:
image

**Comment by PaulHax** [comment]
Lets continue the conversation here: https://github.com/Kitware/VolView/pull/539

**Pull request closed without merging**
